env:
  commonjs: true
  node: true
extends:
  - airbnb-base
  - plugin:flowtype/recommended
  - prettier
parser: babel-eslint
plugins:
  - flowtype
rules:
  quotes:
    - error
    - double
  linebreak-style:
    - off
  flowtype/no-types-missing-file-annotation: off
